# Generated by Django 2.2.5 on 2019-12-24 06:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qiantai', '0002_auto_20191219_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='qiantai.Food', verbose_name='菜品ID'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='qiantai.Order', verbose_name='订单ID'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='state',
            field=models.CharField(max_length=8, verbose_name='完成状态'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='kitchen.Station', verbose_name='所属工位ID'),
        ),
        migrations.AlterField(
            model_name='food',
            name='available',
            field=models.BooleanField(default=True, verbose_name='可销售'),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(upload_to='static/upload/', verbose_name='菜品图片地址'),
        ),
        migrations.AlterField(
            model_name='food',
            name='material',
            field=models.ManyToManyField(through='warehouse.Bom', to='warehouse.Material', verbose_name='原料'),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=16, unique=True, verbose_name='菜品名'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='food',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='qiantai.FoodType', verbose_name='类别'),
        ),
    ]
