# Generated by Django 2.2.5 on 2019-12-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qiantai', '0003_auto_20191224_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='num',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
    ]
