# Generated by Django 3.0 on 2019-12-19 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('phone', models.CharField(max_length=32, verbose_name='电话')),
                ('performance', models.IntegerField(null=True, verbose_name='绩效')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='工资')),
            ],
            options={
                'verbose_name': '员工表',
                'verbose_name_plural': '员工表',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='职位名称')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='岗位工资')),
            ],
            options={
                'verbose_name': '职位表',
                'verbose_name_plural': '职位表',
            },
        ),
        migrations.CreateModel(
            name='Distribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=300, verbose_name='工作时间段')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.Employee', verbose_name='员工ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.Job', verbose_name='职位ID')),
            ],
            options={
                'verbose_name': '排班表',
                'verbose_name_plural': '排班表',
            },
        ),
    ]
