# Generated by Django 2.2.5 on 2020-01-06 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import personnel.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account',
            field=models.ForeignKey(default=personnel.models.get_temp_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='distribute',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribute', to='personnel.Employee', verbose_name='员工ID'),
        ),
        migrations.AlterField(
            model_name='distribute',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distribute', to='personnel.Job', verbose_name='职位ID'),
        ),
    ]
