# Generated by Django 2.2.5 on 2020-01-06 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import personnel.models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_auto_20200106_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='account',
            field=models.ForeignKey(default=personnel.models.get_temp_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='账号ID'),
        ),
    ]
