# Generated by Django 3.0 on 2019-12-19 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
        ('qiantai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.Employee', verbose_name='人员ID')),
            ],
            options={
                'verbose_name': '领料单',
                'verbose_name_plural': '领料单',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.Employee', verbose_name='人员ID')),
            ],
            options={
                'verbose_name': '入库单',
                'verbose_name_plural': '入库单',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='物料名')),
                ('type', models.CharField(max_length=16, verbose_name='类别')),
                ('unit', models.CharField(max_length=16, verbose_name='单位')),
                ('gd', models.IntegerField(verbose_name='数量')),
            ],
            options={
                'verbose_name': '物料单',
                'verbose_name_plural': '物料单',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='采购日期')),
                ('term', models.DateTimeField(null=True, verbose_name='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('method', models.CharField(max_length=16, null=True, verbose_name='方式')),
                ('paid', models.BooleanField(default=False, verbose_name='已支付')),
                ('received', models.BooleanField(default=False, verbose_name='已到货')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.Employee', verbose_name='采购人员ID')),
            ],
            options={
                'verbose_name': '采购单',
                'verbose_name_plural': '采购单',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='供应商名')),
                ('charger', models.CharField(max_length=32, verbose_name='联系人')),
                ('phone', models.CharField(max_length=32, verbose_name='联系电话')),
                ('address', models.CharField(max_length=32, verbose_name='地址')),
            ],
            options={
                'verbose_name': '供应商',
                'verbose_name_plural': '供应商',
            },
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('md', models.DateTimeField(verbose_name='保质期')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Material', verbose_name='物料ID')),
            ],
            options={
                'verbose_name': '库存单',
                'verbose_name_plural': '库存单',
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='单价')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('left', models.IntegerField(default=0, verbose_name='')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Material', verbose_name='所属物料单ID')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Purchase', verbose_name='所属采购单ID')),
            ],
            options={
                'verbose_name': '采购明细',
                'verbose_name_plural': '采购明细',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Supplier', verbose_name='供应商ID'),
        ),
        migrations.CreateModel(
            name='Junk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('reason', models.CharField(max_length=300, verbose_name='报废原因')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='报废日期')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Storage', verbose_name='库存ID')),
            ],
            options={
                'verbose_name': '报废单',
                'verbose_name_plural': '报废单',
            },
        ),
        migrations.CreateModel(
            name='EntryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Entry', verbose_name='入库单ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Material', verbose_name='物料ID')),
            ],
            options={
                'verbose_name': '入库详单',
                'verbose_name_plural': '入库详单',
            },
        ),
        migrations.CreateModel(
            name='DeliveryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Delivery', verbose_name='领料单ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Material', verbose_name='物料ID')),
            ],
            options={
                'verbose_name': '领料详单',
                'verbose_name_plural': '领料详单',
            },
        ),
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qiantai.Food', verbose_name='菜品ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.Material', verbose_name='物料ID')),
            ],
            options={
                'verbose_name': '物料清单',
                'verbose_name_plural': '物料清单',
            },
        ),
    ]
