# Generated by Django 2.2.5 on 2019-12-31 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='qiantai.Food', verbose_name='菜品ID'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom', to='warehouse.Material', verbose_name='物料ID'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='personnel.Employee', verbose_name='人员ID'),
        ),
        migrations.AlterField(
            model_name='deliverydetail',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_detail', to='warehouse.Delivery', verbose_name='领料单ID'),
        ),
        migrations.AlterField(
            model_name='deliverydetail',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_detail', to='warehouse.Material', verbose_name='物料ID'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='personnel.Employee', verbose_name='人员ID'),
        ),
        migrations.AlterField(
            model_name='entrydetail',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_detail', to='warehouse.Entry', verbose_name='入库单ID'),
        ),
        migrations.AlterField(
            model_name='entrydetail',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_detail', to='warehouse.Material', verbose_name='物料ID'),
        ),
        migrations.AlterField(
            model_name='junk',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junk', to='warehouse.Storage', verbose_name='库存ID'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='personnel.Employee', verbose_name='采购人员ID'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='warehouse.Supplier', verbose_name='供应商ID'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_detail', to='warehouse.Material', verbose_name='所属物料单ID'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_detail', to='warehouse.Purchase', verbose_name='所属采购单ID'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='warehouse.Material', verbose_name='物料ID'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.CharField(max_length=300, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='charger',
            field=models.CharField(max_length=16, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='联系电话'),
        ),
    ]
