# Generated by Django 2.2.5 on 2020-01-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20191231_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='num',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='签订日期'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='method',
            field=models.CharField(max_length=16, null=True, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='term',
            field=models.DateTimeField(null=True, verbose_name='收货期限'),
        ),
    ]
