# Generated by Django 2.2.5 on 2020-01-09 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20200107_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': '采购入库单', 'verbose_name_plural': '采购入库单'},
        ),
        migrations.AlterModelOptions(
            name='deliverydetail',
            options={'verbose_name': '采购入库详单', 'verbose_name_plural': '采购入库详单'},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': '领料单', 'verbose_name_plural': '领料单'},
        ),
        migrations.AlterModelOptions(
            name='entrydetail',
            options={'verbose_name': '领料详单', 'verbose_name_plural': '领料详单'},
        ),
        migrations.RemoveField(
            model_name='deliverydetail',
            name='entry',
        ),
        migrations.AddField(
            model_name='deliverydetail',
            name='delivery',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_detail', to='warehouse.Delivery', verbose_name='入库单ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='领料时间'),
        ),
        migrations.AlterField(
            model_name='entrydetail',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_detail', to='warehouse.Entry', verbose_name='领料单ID'),
        ),
        migrations.AlterField(
            model_name='junk',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='junk', to='warehouse.Storage', verbose_name='库存编号'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='left',
            field=models.IntegerField(default=0, verbose_name='未到货数量'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='入库日期'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='warehouse.Material', verbose_name='物料编号'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='md',
            field=models.DateTimeField(verbose_name='生产日期'),
        ),
    ]
