# Generated by Django 3.0 on 2019-12-19 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(verbose_name='加工时间')),
            ],
            options={
                'verbose_name': '任务分配',
                'verbose_name_plural': '任务分配',
            },
        ),
        migrations.CreateModel(
            name='Prepare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0, verbose_name='数量')),
                ('used', models.IntegerField(default=0, verbose_name='已售')),
                ('total', models.IntegerField(default=0, verbose_name='总计')),
                ('date', models.TimeField(auto_now=True, verbose_name='有效时间')),
            ],
            options={
                'verbose_name': '预备菜品',
                'verbose_name_plural': '预备菜品',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.Employee', verbose_name='员工ID')),
            ],
            options={
                'verbose_name': '工位',
                'verbose_name_plural': '工位',
            },
        ),
    ]
